/**
 * Appends all TVET institutions to data/institutions.json.
 * IDs auto-increment from max existing ID + 1.
 * Names containing "National Polytechnic" get type "National Polytechnic";
 * all others get "Technical and Vocational College (TVET)".
 */

const fs = require('fs');
const path = require('path');

const institutionsPath = path.join(__dirname, '..', 'data', 'institutions.json');
const existing = JSON.parse(fs.readFileSync(institutionsPath, 'utf8'));

const maxId = Math.max(...existing.map((i) => i.id));

const ACCREDITOR = 'Technical and Vocational Education and Training Authority (TVETA)';
const SOURCE = 'https://www.tvetkenya.co.ke/institutions/';

// county_id → county_name (exact names from counties.json)
const COUNTIES = {
  1: 'Mombasa', 2: 'Kwale', 3: 'Kilifi', 4: 'Tana River', 5: 'Lamu',
  6: 'Taita Taveta', 7: 'Garissa', 8: 'Wajir', 9: 'Mandera', 10: 'Marsabit',
  11: 'Isiolo', 12: 'Meru', 13: 'Tharaka-Nithi', 14: 'Embu', 15: 'Kitui',
  16: 'Machakos', 17: 'Makueni', 18: 'Nyandarua', 19: 'Nyeri', 20: 'Kirinyaga',
  21: "Murang'a", 22: 'Kiambu', 23: 'Turkana', 24: 'West Pokot', 25: 'Samburu',
  26: 'Trans-Nzoia', 27: 'Uasin Gishu', 28: 'Elgeyo Marakwet', 29: 'Nandi',
  30: 'Baringo', 31: 'Laikipia', 32: 'Nakuru', 33: 'Narok', 34: 'Kajiado',
  35: 'Kericho', 36: 'Bomet', 37: 'Kakamega', 38: 'Vihiga', 39: 'Bungoma',
  40: 'Busia', 41: 'Siaya', 42: 'Kisumu', 43: 'Homa Bay', 44: 'Migori',
  45: 'Kisii', 46: 'Nyamira', 47: 'Nairobi',
};

// [county_id, name] pairs — grouped by county for readability
const RAW = [
  // BARINGO (30)
  [30, 'Baringo Technical College'],
  [30, 'Cheberen VTC'],
  [30, 'Emining TTI'],
  [30, 'Kabartonjo VTC'],
  [30, 'Kenya School of Government Baringo Campus'],
  [30, 'Kituro VTC'],
  [30, 'Maji Moto VTC'],
  [30, 'Marigat VTC'],
  [30, 'Mogotio VTC'],
  [30, 'Sogorik VTC'],

  // BOMET (36)
  [36, 'Sot Technical Training Institute'],
  [36, 'Bingwa Youth Polytechnic'],
  [36, 'Boito VTC'],
  [36, 'Chebilat VTC'],
  [36, 'Emkwen VTC'],
  [36, 'Kabisoge VTC'],
  [36, 'Kaboson VTC'],
  [36, "Kamung'ei VTC"],
  [36, 'Kaplong VTC'],
  [36, 'Kapsabul VTC'],
  [36, 'Kaptebengwet VTC'],
  [36, 'Kimarwandi VTC'],
  [36, 'Kiplelji VTC'],
  [36, 'Komirmir VTC'],
  [36, 'Konoin TTI'],
  [36, 'Manaret VTC'],
  [36, 'Seanin VTC'],
  [36, 'Siomo VTC'],
  [36, 'Siwot VTC'],
  [36, 'Solyot VTC'],
  [36, 'Sotik Technical Training Institute'],
  [36, 'Tegat VTC'],

  // BUNGOMA (39)
  [39, 'Apokor VTC'],
  [39, 'Bitobo VTC'],
  [39, 'Bukembe Vocational Center'],
  [39, 'Chebukwabi VTC'],
  [39, 'Friends VTC Mihuu'],
  [39, 'Kamasielo VTC'],
  [39, 'Khasoko VTC'],
  [39, 'Khelela VTC'],
  [39, 'Kibabii VTI'],
  [39, 'Kisiwa VTC'],
  [39, 'Kisongo VTC'],
  [39, 'Lwandanyi VTC'],
  [39, 'Machakha VTC'],
  [39, 'Machwele VTC'],
  [39, 'Magemo VTC'],
  [39, 'Malakisi VTC'],
  [39, 'Matili TTI'],
  [39, 'Matulo VTC'],
  [39, 'Mufule VTC'],
  [39, 'Mungore VTC'],
  [39, 'Musakasa TTI'],
  [39, 'Muteremuko VTC'],
  [39, 'Naitiri VTC'],
  [39, 'Namirembe VTC'],
  [39, "Sang'alo Institute of Science and Technology"],
  [39, 'Sinoko VTC'],
  [39, 'Sirare VTC'],
  [39, 'Sirisia VTC'],
  [39, 'Sitabicha Vocational Center'],
  [39, 'Sosio VTC'],
  [39, 'St Teresa Musoli Vocational Center'],
  [39, 'St Theresa Kabula'],
  [39, 'Tongaren VTC'],
  [39, 'Wabukhonyi VTC'],
  [39, 'Wekelekha Vocational Center'],

  // BUSIA (40)
  [40, 'Amaase VTC'],
  [40, 'Amagoro VTC'],
  [40, 'Bumbe TTI'],
  [40, 'Busagwa VTC'],
  [40, 'Busia VTC'],
  [40, 'Butunyi VTC'],
  [40, 'Esidende VTC'],
  [40, 'Igara ADC VTC'],
  [40, 'Khayo VTC'],
  [40, 'Matayos VTC'],
  [40, 'Nambale VTC'],
  [40, 'Oserut VTC'],
  [40, 'ST Marys Ganga VTC'],

  // ELGEYO MARAKWET (28)
  [28, 'Chebara VTC'],
  [28, 'Chepkorio VTC'],
  [28, 'Chesongoch VTC'],
  [28, 'Flax VTC'],
  [28, 'Iten VTC'],
  [28, 'Kapcherop VTC'],
  [28, 'Kibirech VTC'],
  [28, 'Kipchawat VTC'],
  [28, 'Kiplabai VTC'],
  [28, 'Kitany VTC'],
  [28, 'Koitilial VTC'],

  // EMBU (14)
  [14, 'Ena VTC'],
  [14, 'Gitare VTC'],
  [14, 'Jeremiah Nyaga Technical'],
  [14, 'Runyenjes TVC'],
  [14, 'St Catherine Kigwambiti VTC'],

  // GARISSA (7)
  [7, 'North Eastern National Polytechnic'],

  // HOMA BAY (43)
  [43, 'Homabay Youth Polytechnic'],
  [43, 'Jwelu Youth Polytechnic'],
  [43, 'Kabuoch VTC'],
  [43, 'Lambwe VTC'],
  [43, 'Langi Youth Polytechnic'],
  [43, 'Mawego TTI'],
  [43, 'Mboga VTC'],
  [43, 'Mfangano VTC'],
  [43, 'Ndiru VTC'],
  [43, 'Nyagwethe VTC'],
  [43, 'Paul Mboya VTC'],
  [43, 'Rukongo VTC'],
  [43, 'Sero VTC'],
  [43, 'Sikri Technical and Vocational College for the Blind and Deaf'],
  [43, 'Sindo VTC'],
  [43, 'St Anne Mawego Youth Polytechnic'],
  [43, 'Waiga VTC'],
  [43, 'Wakiaga VTC'],
  [43, 'Waondo VTC'],

  // ISIOLO (11)
  [11, 'Uhuru Vocational Training College'],

  // KAJIADO (34)
  [34, 'Isinya VTC'],
  [34, 'Masai TTI'],
  [34, 'Meto VTC'],
  [34, 'Namelok Youth Polytechnic'],
  [34, 'Olekasasi VTC'],
  [34, 'Ruiru Gikonyo Memorial Institute for Technical Skills'],

  // KAKAMEGA (37)
  [37, 'Bukura Agricultural College'],
  [37, 'Bushiangala TTI'],
  [37, 'Butere TVC'],
  [37, 'Kabras County VTC'],
  [37, 'Lugala County VTC'],
  [37, 'Mabanga Youth Polytechnic'],
  [37, 'Malaha County VTC'],
  [37, 'Mautuma VTC'],
  [37, 'Mumbetsa County Polytechnic'],
  [37, 'Nzoia County Polytechnic'],
  [37, 'Raphael Malimili Youth Polytechnic'],
  [37, 'Rural Craft Training Centre NYS Turbo'],
  [37, 'SA Chombeli County Polytechnic'],
  [37, 'Shagungu VTC'],
  [37, 'Shamberere TTI'],
  [37, 'Shilolavakhali County VTC'],
  [37, 'Solongo VTC'],
  [37, 'St Maurice Mwira County VTC'],
  [37, 'St Peters Emulakha Polytechnic'],
  [37, 'The Sigalagala National Polytechnic'],

  // KERICHO (35)
  [35, 'Bureti TTI'],
  [35, 'Chebirirbei VTC'],
  [35, 'Kipsamumgut VTC'],
  [35, 'Kiptere VTC'],
  [35, 'St Kizito Special Needs Vocational Training Center'],
  [35, 'Toroton VTC'],

  // KIAMBU (22)
  [22, 'Gokoe VTC'],
  [22, 'Gitiha VTC'],
  [22, 'Gituamba VTC'],
  [22, 'Juja Farm VTC'],
  [22, 'Kagumo-ini VTC'],
  [22, 'Kairi VTC'],
  [22, 'Kamirithu VTC'],
  [22, 'Kanyariri VTC'],
  [22, 'Karatu VTC'],
  [22, 'Karingari VTC'],
  [22, 'Kinoo VTC'],
  [22, 'Komothai VTC'],
  [22, 'Makongeni Educational VTC'],
  [22, 'Mangu VTC'],
  [22, 'Mbichi VTC'],
  [22, 'Muguga VTC'],
  [22, 'Munyu-ini VTC'],
  [22, 'Ndenderu VTC'],
  [22, 'Nyaga VTC'],
  [22, 'Nyanduma VTC'],
  [22, 'Riabai VTC'],
  [22, 'Riuki Youth Polytechnic'],
  [22, 'ST BOSCO VTC'],
  [22, 'St Joseph The Worker Thuita VTC'],
  [22, 'Thika TTI'],
  [22, 'Thogoto VTC'],
  [22, 'Uthiru VTC'],
  [22, 'Wabeni VTC'],

  // KILIFI (3)
  [3, 'Gede VTC'],
  [3, 'Godoma Technical and Vocational College'],
  [3, 'Jilore VTC'],
  [3, 'Kakuyuni VTC'],
  [3, 'Mapimo VTC'],
  [3, 'Mariakani Vocational Education and Training Center'],
  [3, 'Mkwajuni VTC'],
  [3, 'Muyeye VTC'],
  [3, 'Mwabayanyundo Youth Polytechnic'],
  [3, 'Mwamutsunga VTC'],
  [3, 'Vitengeni VTC'],
  [3, 'Weru Technical and Vocational College'],
  [3, 'Marafa VTC'],

  // KIRINYAGA (20)
  [20, 'Kaitheri VTC'],
  [20, 'Kamugua VTC'],
  [20, 'Kiabwe VTC'],
  [20, 'Kiambatha VTC'],
  [20, 'Kiamikuyu VTC'],
  [20, 'Kiamuthambi VTC'],
  [20, 'Kibingoti VTC'],
  [20, 'Kimweas VTC'],
  [20, 'Mucii Wa Urata VTC'],
  [20, 'Mutitu VTC'],
  [20, 'Ndiriti VTC'],

  // KISII (45)
  [45, 'Keroka TTI'],
  [45, 'The Kisii National Polytechnic'],

  // KISUMU (42)
  [42, 'ACK Kigoche'],
  [42, 'Archbishop Okoth VTC'],
  [42, 'Bondo TVC'],
  [42, 'Chwa Youth Polytechnic'],
  [42, 'Karateng VTC'],
  [42, 'Katito Youth Polytechnic'],
  [42, 'Kitambo VTC'],
  [42, "Lung'a Youth Polytechnic"],
  [42, 'Mariwa VTC'],
  [42, "Nyang'oma Youth Polytechnic"],
  [42, 'Obange Youth Polytechnic'],
  [42, 'Railway Training Institute Kisumu'],
  [42, 'Ramogi Institute of Advanced Technology'],
  [42, 'Sianda Youth Polytechnic'],
  [42, 'The Kisumu National Polytechnic'],
  [42, 'Tom Mboya Labor College'],

  // KITUI (15)
  [15, 'Frances Taylor Youth Polytechnic'],
  [15, 'Gai VTC'],
  [15, 'Ikutha VTC'],
  [15, 'Ithiani VTC'],
  [15, 'Kamanyi VTC'],
  [15, 'Kathivo VTC'],
  [15, 'Katse VTC'],
  [15, 'Katulani VTC'],
  [15, 'Katwala VTC'],
  [15, 'Kinakoni VTC'],
  [15, 'Kisasi VTC'],
  [15, 'Kyatune VTC'],
  [15, 'Kyuso VTC'],
  [15, 'Matinyani VTC'],
  [15, 'Mavia VTC'],
  [15, 'Migwani Family Helper VTC'],
  [15, 'Migwani VTC'],
  [15, 'Mui VTC'],
  [15, 'Mulango VTC'],
  [15, 'Mutomo VTC'],
  [15, 'Mutonguni VTC'],
  [15, 'Mwingi Baptist VTC'],
  [15, 'St Joseph Mwambiu VTC'],
  [15, 'Syongila VTC'],
  [15, 'Tseikuru TTI Mwingi'],

  // KWALE (2)
  [2, 'Diani VTC'],
  [2, 'Makina VTC'],
  [2, 'Mamba VTC'],
  [2, 'Manda VTC'],
  [2, 'Mavirivirini VTC'],
  [2, 'Mazeras Youth Polytechnic'],
  [2, 'Mrima VTC'],
  [2, 'Mwabungo VTC'],
  [2, 'Tiwi VTC'],
  [2, 'Ukunda VTC'],
  [2, 'Vanga Youth Polytechnic'],

  // LAIKIPIA (31)
  [31, 'Nanyuki VTC'],
  [31, 'Sipili VTC'],

  // MACHAKOS (16)
  [16, 'Kituluni VTC'],
  [16, 'ABC Kivi VTC'],
  [16, 'Athi River VTC'],
  [16, 'Ekalakala VTC'],
  [16, 'Kaluluni VTC'],
  [16, 'Kalumoni VTC'],
  [16, 'Katangi VTC'],
  [16, 'Katine TTI'],
  [16, 'Kimutwa VTC'],
  [16, 'Kioyweni VTC'],
  [16, 'Kithaayoni VTC'],
  [16, 'Kithuluni VTC'],
  [16, 'Komarok VTC'],
  [16, 'Kyamutwoii SA VTC'],
  [16, 'Kyamwee VTC'],
  [16, 'Kyeleni VTC'],
  [16, 'Kyemutheke VTC'],
  [16, 'Kyevaluki VTC'],
  [16, 'Lumbwa Salvation Army VTC'],
  [16, 'Lumbwa VTC'],
  [16, 'Machakos Technical Institute for the Blind'],
  [16, 'Masii VTC'],
  [16, 'Masinga VTC'],
  [16, 'Matuu VTC'],
  [16, 'Miseleni Salvation Army VTC'],
  [16, 'Mutondoni VTC'],
  [16, 'Mutuyu VTC'],
  [16, 'Ndalani Youth Polytechnic'],
  [16, 'Ndithini VTC'],
  [16, 'Ngelani VTC'],
  [16, 'NYS Yatta School of Agriculture'],
  [16, 'Vyulia VTC'],
  [16, 'Yathui VTC'],

  // MAKUENI (17)
  [17, 'ABCU Katuuni Youth Polytechnic'],
  [17, 'David Mbithi Wambuli Technical and Vocational College'],
  [17, 'Isovya VTC'],
  [17, 'Ivuleni VTC'],
  [17, 'Kathonnzeni VTC'],
  [17, 'Kauti Youth Polytechnic'],
  [17, 'Kisingo VTC'],
  [17, 'Kyemwole Youth Polytechnic'],
  [17, 'Mavindini VTC'],
  [17, 'Ndeini VTC'],
  [17, 'Nduluku VTC'],
  [17, "Ng'etha VTC"],
  [17, 'Spring Hill Kwakakulu VTC'],
  [17, 'Tulimali Youth Polytechnic'],
  [17, 'Ukia Youth Polytechnic'],
  [17, 'Uvileni VTC'],
  [17, 'Wote TTI'],

  // MANDERA (9)
  [9, 'Mandera VTC'],

  // MARSABIT (10)
  [10, 'Merille VTC'],
  [10, 'Moyale VTC'],
  [10, 'Obbu VTC'],
  [10, 'Saku VTC'],
  [10, 'Umuro VTC'],

  // MERU (12)
  [12, 'Chuka TTI'],
  [12, 'Ithamare VTC'],
  [12, 'Githongo Youth Polytechnic'],
  [12, 'Gitie Vocational Training College'],
  [12, 'Kagwampungu VTC'],
  [12, 'Kanyakine VTC'],
  [12, 'Karumo TTI'],
  [12, 'Karurune VTC'],
  [12, 'Kianjai VTC'],
  [12, 'Kiirua TTI'],
  [12, 'Kiirua VTC'],
  [12, 'Kithiiri Vocational Training College'],
  [12, 'Kithoka VTC'],
  [12, 'Koome VTC'],
  [12, 'Maua Vocational Training College'],
  [12, 'Meru Institute of Business Studies'],
  [12, 'Mitunguu TTI'],
  [12, 'Mituntu VTC'],
  [12, 'Mukiria TTI'],
  [12, 'Murugi VTC'],
  [12, 'Muthara VTC'],
  [12, 'Mwiteria VTC'],
  [12, 'Nkabune TTI'],
  [12, 'Ruibi Youth Polytechnic'],
  [12, 'Salama VTC'],
  [12, 'The Meru National Polytechnic'],

  // MIGORI (44)
  [44, 'Awendo Marindi Youth Polytechnic'],
  [44, 'Biticha VTC'],
  [44, 'Bware VTC'],
  [44, 'Chinato Vocational and Educational Training Center'],
  [44, 'Gamasisi VTC'],
  [44, 'Kababu VTC'],
  [44, 'Macalder VTC'],
  [44, 'Manyatta VTC'],
  [44, 'Migori VTC'],
  [44, 'Ntimaru Youth Polytechnic'],
  [44, 'Siala TTI'],
  [44, 'Uriri VTC'],

  // MOMBASA (1)
  [1, 'Ahmed Shahame Mwidani Technical and Vocational College'],
  [1, 'Bandari College'],
  [1, 'Kenya Coast National Polytechnic'],
  [1, 'Kenya School of Revenue Administration'],
  [1, 'Mtongwe VTC'],

  // MURANG'A (21)
  [21, 'Mathioya Technical Vocational College'],
  [21, 'Baraka VTC'],
  [21, 'Gatanga Technical Vocational College'],
  [21, 'Gatara VTC'],
  [21, 'Gikindu Youth Polytechnic'],
  [21, 'Gikomora VTC'],
  [21, 'Githagara VTC'],
  [21, 'Ichagaki VTC'],
  [21, 'Kaganda VTC'],
  [21, 'Kahuti VTC'],
  [21, 'Kamahuha VTC'],
  [21, 'Kambara VTC'],
  [21, 'Kambirwa VTC'],
  [21, 'Kambiti VTC'],
  [21, 'Kamukabi Youth Polytechnic'],
  [21, 'Kamune VTC'],
  [21, 'Kangari VTC'],
  [21, 'Kangema Youth Polytechnic'],
  [21, 'Kanyaira Youth Polytechnic'],
  [21, 'Karuru VTC'],
  [21, 'Kibaaka VTC'],
  [21, 'Kigumo VTC'],
  [21, 'KIIRIANGORO VTC'],
  [21, 'Kirangari VTC'],
  [21, 'Kirwara VTC'],
  [21, 'Makomboki VTC'],
  [21, 'Mbugiti VTC'],
  [21, 'Michuki TTI'],
  [21, 'Mukangu VTC'],
  [21, 'Mutitu VTC'],
  [21, 'Mwagu Vocational Centre'],
  [21, 'Ndutumi VTC'],
  [21, 'Njii-ithatu VTC'],
  [21, 'Rau VTC'],
  [21, 'Thuita VTC'],
  [21, 'Wahundura VTC'],
  [21, 'Wanjohi Youth Polytechnic'],

  // NAIROBI (47)
  [47, 'Administration Police Training College'],
  [47, 'Animal Health and Industry Training Institute AHITI Kabete'],
  [47, 'Centre for Tourism Training and Research'],
  [47, 'Defence Forces Technical College DEFTEC'],
  [47, 'East African School of Aviation'],
  [47, 'GSU Training School'],
  [47, 'Institute for Meteorological Training and Research'],
  [47, 'Institute of Energy Studies and Research'],
  [47, 'Kangemi VTC'],
  [47, 'Karen Technical Training Institute for the Deaf'],
  [47, 'Kenya Institute of Surveying and Mapping'],
  [47, 'Kenya School of Monetary Studies'],
  [47, 'Kenya Technical Trainers College'],
  [47, 'Kenya Water Institute'],
  [47, 'Kiwanja VTC'],
  [47, 'Meat Training Institute'],
  [47, 'Nairobi Technical Training Institute'],
  [47, 'National Youth Service Institute of Business Studies'],
  [47, 'NYS Engineering Institute'],
  [47, 'NYS Textile and Garment Making Technical Institute'],
  [47, 'NYS Vocational Training Institute'],
  [47, 'C Kinyanjui Technical Training Institute'],
  [47, 'Railway Training Institute Nairobi'],
  [47, 'Regional Centre for Mapping of Development Resources'],
  [47, 'The Kabete National Polytechnic'],
  [47, 'Waithaka VTC'],

  // NAKURU (32)
  [32, 'Bahati Institute of Business and Administration Studies'],
  [32, 'Barut Youth Polytechnic'],
  [32, 'Chemare VTC'],
  [32, 'Cheptuech VTC'],
  [32, 'Dairy Training Institute'],
  [32, 'Dundori VTC'],
  [32, 'House of Plenty VTC'],
  [32, 'Kenya Industrial Training Institute Nakuru'],
  [32, 'Kikopey VTC'],
  [32, 'KWS Training Institute'],
  [32, 'Lion Hill VTC'],
  [32, 'Mirera VTC'],
  [32, 'Molo VTC'],
  [32, 'Morendat Institute of Oil and Gas'],
  [32, 'Muteithia VTC'],
  [32, 'Nakuru Youth Polytechnic'],
  [32, 'NYS Advanced Building School'],
  [32, 'NYS School of Catering Gilgil'],
  [32, 'NYS School of Fashion Design Naivasha'],
  [32, 'Rift Valley Institute of Science and Technology'],
  [32, 'Rift Valley Institute of Science and Technology Nakuru Town'],
  [32, 'Rongai VTC'],
  [32, 'SAPTET VTC'],
  [32, 'Subukia VTC'],
  [32, 'Wanyororo VTC'],

  // NANDI (29)
  [29, 'Aldai TTI'],
  [29, 'Cheptarit VTC'],
  [29, 'Kaiboi TTI'],
  [29, 'Kaplamai VTC'],
  [29, 'Kaptel VTC'],
  [29, 'Kurgung VTC'],
  [29, 'Mugen VTC'],
  [29, "Ol'lessos TTI"],
  [29, 'Sigilai VTC'],
  [29, 'Sirwa Yala VTC'],
  [29, 'Augustine Kipsebwo VTC'],
  [29, 'Tengaratwet VTC'],

  // NAROK (33)
  [33, 'Enelerai VTC'],
  [33, 'Ilmotiok VTC'],
  [33, 'Kapweria VTC'],
  [33, 'Kilgoris VTC'],
  [33, 'Maasai Mara Technical and Vocational College'],
  [33, 'Nairegie Enkare VTC'],
  [33, 'Narok West TTI'],
  [33, 'Narok VTC'],
  [33, 'Narok West Technical Training Institute'],

  // NYANDARUA (18)
  [18, 'Kahoro VTC'],
  [18, 'Kinangop VTC'],
  [18, 'Lereshwa Youth Polytechnic'],
  [18, 'Leshau VTC'],
  [18, 'Melangine VTC'],
  [18, 'Miharati VTC'],
  [18, 'Mukeu VTC'],
  [18, 'Ngorika VTC'],
  [18, 'Njabini VTC'],
  [18, 'Nyandarua Institute of Science and Technology'],
  [18, 'Olkalou Youth Polytechnic'],
  [18, 'Rurii VTC'],
  [18, 'Shamata VTC'],

  // NYAMIRA (46)
  [46, 'Bigege VTC'],
  [46, 'Bonyonyu VTC'],
  [46, 'Ekerubo Gietai TTI'],
  [46, 'ELCK Bobembe VTC'],
  [46, 'Gesima VTC'],
  [46, 'Kegwanda VTC'],
  [46, 'Kenyerere VTC'],
  [46, "Kiang'ende VTC"],
  [46, 'Kiendege VTC'],
  [46, 'Kiobwoge VTC'],
  [46, 'Kiogutwa VTC'],
  [46, 'Matongo VTC'],
  [46, 'Misambi VTC'],
  [46, 'Morako VTC'],
  [46, 'Nyaikuro VTC'],
  [46, 'Ritibo VTC'],
  [46, 'Ritongo VTC'],
  [46, 'St Albert Bundo VTC'],
  [46, 'St Stephen Ekerubo VTC'],
  [46, 'St Elizabeth Embaro VTC'],
  [46, 'St Peters Geteni VTC'],

  // NYERI (19)
  [19, 'Gachika Youth Center'],
  [19, 'Githiru Youth Polytechnic'],
  [19, 'Karatina VTC'],
  [19, 'Kenya Police College'],
  [19, 'Mathenge TTI'],
  [19, 'Mathira Technical and Vocational College'],
  [19, 'Mukurwe-ini TTI'],
  [19, 'Nairutia VTC'],
  [19, 'Rukira VTC'],
  [19, 'The Nyeri National Polytechnic'],
  [19, 'Watuka VTC'],

  // SAMBURU (25)
  [25, 'Maralal VTC'],

  // SIAYA (41)
  [41, "St Joseph's Technical Institute for The Deaf Nyang'oma"],
  [41, 'Aiden VTC'],
  [41, 'Boi VTC'],
  [41, 'Bondo Technical Training Institute'],
  [41, 'Kisendo VTC'],
  [41, "Kobong' Youth Polytechnic"],
  [41, 'Liganywa VTC'],
  [41, 'Lucy Onono VTC'],
  [41, 'Mahaya VTC'],
  [41, 'Mindhine VTC'],
  [41, 'Ndere VTC'],
  [41, 'Ndira Youth Polytechnic'],
  [41, "Ng'iya VTC"],
  [41, 'Nyala VTC'],
  [41, 'Sega VTC'],
  [41, 'Siaya Institute of Technology'],
  [41, 'Sigul VTC'],

  // TAITA TAVETA (6)
  [6, 'Bungule VTC'],
  [6, 'Challa VTC'],
  [6, 'Chumvini VTC'],
  [6, 'Coast Institute of Technology'],
  [6, 'Ghazi VTC'],
  [6, 'Kidaya Ngerenyi VTC'],
  [6, 'Kighombo VTC'],
  [6, 'Kiloghwa VTC'],
  [6, 'Mbale VTC'],
  [6, 'Mnamu VTC'],
  [6, 'Msau VTC'],
  [6, 'Mselia VTC'],
  [6, 'Mwachawaza VTC'],
  [6, 'Mwagafwa VTC'],
  [6, 'Mwambiti VTC'],
  [6, 'Mwanda VTC'],
  [6, 'Mwanjila VTC'],
  [6, 'Mwarungu VTC'],
  [6, "Rong'e Juu VTC"],
  [6, 'Sagalla VTC'],
  [6, 'Tausa VTC'],
  [6, 'Taveta VTC'],
  [6, 'Voi VTC'],
  [6, 'Wongonyi VTC'],

  // TANA RIVER (4)
  [4, 'Maziwa Youth Polytechnic'],

  // THARAKA-NITHI (13)
  [13, 'ACK Uthaini VTC'],
  [13, 'Marimanti VTC'],
  [13, 'Muthambi Youth Polytechnic'],
  [13, 'Ndunguri VTC'],
  [13, 'Nguruki VTC'],
  [13, 'NICA Karigini VTC'],
  [13, 'Weru VTC'],

  // TRANS-NZOIA (26)
  [26, 'Andersen VTC'],
  [26, 'Kapchepsir VTC'],
  [26, 'Kiminini VTC'],
  [26, 'Kitale VTC'],
  [26, 'Kwanza VTC'],
  [26, 'Machungwa VTC'],
  [26, 'Matisi VTC'],
  [26, 'Matunda VTC'],
  [26, 'Section Six VTC'],
  [26, 'Sikhendu VTC'],
  [26, 'Sitatunga VTC'],
  [26, "St Joseph's Makutano Vocational Training"],
  [26, 'The Kitale National Polytechnic'],
  [26, 'Waitaluk VTC'],

  // TURKANA (23)
  [23, 'Kaaleng VTC'],
  [23, 'Kalokol VTC'],
  [23, 'Lodwar VTC'],
  [23, 'Lokichar VTC'],
  [23, 'Lokori VTC'],
  [23, 'Lorogum VTC'],

  // UASIN GISHU (27)
  [27, 'Ainabkoi VTC'],
  [27, 'Arise and Shine VTC'],
  [27, 'Eldoret VTC'],
  [27, 'Koshin TTI'],
  [27, 'Mioro VTC'],
  [27, 'Mugondoi VTC'],
  [27, 'Rift Valley TTI'],
  [27, 'Sergoek VTC'],
  [27, 'Sesia VTC'],
  [27, 'The Eldoret National Polytechnic'],

  // VIHIGA (38)
  [38, 'Boyani VTC'],
  [38, 'Busaina VTC'],
  [38, 'Ebusiralo VTC'],
  [38, 'Ematete VTC'],
  [38, 'Friends College Kaimosi Institute of Technology'],
  [38, 'Gavudia VTC'],
  [38, 'Gimomoi Salvation Army VTC'],
  [38, 'Givigoi VTC'],
  [38, 'Jepkose VTC'],
  [38, 'Kaimosi Friends VTC'],
  [38, 'Karadinin VTC'],
  [38, 'Keveye VTC'],
  [38, 'Kitulu VTC'],
  [38, 'Lotego VTC'],
  [38, 'Maseno School of Nursing'],
  [38, 'Maseno Youth Polytechnic'],
  [38, 'Muhudu VTC'],
  [38, 'North Maragoli VTC'],
  [38, 'Nzalwa VTC'],
  [38, 'South Maragoli VTC'],
  [38, 'St Peters Hambale VTC'],
  [38, 'Vigetse VTC'],

  // WEST POKOT (24)
  [24, 'Kapenguria VTC'],
];

function getType(name) {
  if (name.includes('National Polytechnic')) return 'National Polytechnic';
  return 'Technical and Vocational College (TVET)';
}

const newEntries = RAW.map(([county_id, name], idx) => ({
  id: maxId + 1 + idx,
  name,
  type: getType(name),
  category: 'Public',
  county_id,
  county_name: COUNTIES[county_id],
  constituency: '',
  address: '',
  postal_code: '',
  phone: '',
  email: '',
  website: '',
  accredited_by: ACCREDITOR,
  source: SOURCE,
  initials: null,
  year_established: null,
  coordinates: { lat: null, lng: null },
}));

const merged = [...existing, ...newEntries];

fs.writeFileSync(institutionsPath, JSON.stringify(merged, null, 2), 'utf8');

const tvetTypes = ['Technical and Vocational College (TVET)', 'National Polytechnic'];
const tvets = newEntries.filter((i) => tvetTypes.includes(i.type));
const polys = newEntries.filter((i) => i.type === 'National Polytechnic');

console.log(`Total entries now: ${merged.length}`);
console.log(`New TVET entries added: ${newEntries.length}`);
console.log(`  National Polytechnics: ${polys.length}`);
console.log(`  TVETs/TTIs/VTCs: ${tvets.length - polys.length}`);
console.log(`  ID range: ${maxId + 1} – ${maxId + newEntries.length}`);
console.log('Polytechnics:');
polys.forEach((p) => console.log(`  ${p.id}: ${p.name}`));
